### Correct request
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Rooney Mara",
  "number": "0999-999-9999"
}

### Missing number
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Rooney Mara",
  "number": ""
}

### Missing name
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "",
  "number": ""
}

### Update existing person
PUT http://localhost:3001/api/persons/698d88af41500376b04d8112
Content-Type: application/json

{ 
  "name": "Rooney Mara", 
  "number": "39-23-6423122"
}
